version: '3.4'

services:
  smarthub.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44319
      - ConnectionString=User ID=postgres;Password=admin;Server=postgres;Port=5432;Database=smarthub;Integrated Security=true; Pooling=true;
      - Seq__ServerUrl=http://seq:5341
      - Seq__ApiKey=1234567890
      - Seq__MinimumLevel=Trace
      - Seq__LevelOverride__Microsoft=Warning
    ports:
      - "49580:80"
      - "44319:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  smarthub.edge:
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=https://+:443;http://+:80
     - ASPNETCORE_HTTPS_PORT=44398
     - kafka_endpoint=kafka:9092
    ports:
      - "44398:443"
      - "49582:80"
    restart: always
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  smarthub.spa:
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=https://+:443;http://+:80
     - ASPNETCORE_HTTPS_PORT=44332
     - NotificationServiceUrl=https://localhost:44335
     - SmartHubApiUrl=https://localhost:44319/api
     - IdentityUrl=https://localhost:44338
    ports:
      - "44332:443"
      - "49581:80"
    volumes:
     - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  smarthub.notificationservice:
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=https://+:443;http://+:80
     - ASPNETCORE_HTTPS_PORT=44335
     - BrokerURI=kafka:9092
     - KafkaConsumerGroupId=notification-consumers
     - RedisURI=redis:6379
    ports:
      - "44335:443"
      - "49583:80"
    volumes:
     - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  smarthub.saverservice:
    environment:
     - BrokerURI=kafka:9092
     - ConnectionString=User ID=postgres;Password=admin;Server=postgres;Port=5432;Database=smarthub;Integrated Security=true; Pooling=true;
     - KafkaConsumerGroupId=storage-consumers
  smarthub.identity:
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=https://+:443;http://+:80
     - ASPNETCORE_HTTPS_PORT=44338
     - ConnectionStrings__Default=User ID = postgres;Password=admin;Server=postgres;Port=5432;Database=smarthub_identity;Integrated Security=true; Pooling=true;
    ports:
     - "44338:443"
     - "49585:80"
    volumes:
     - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  redis:
    ports:
     - "6379:6379"
  postgres:
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_database:/var/lib/postgresql/data:Z
  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "80:80"
      - "5341:5341"
    volumes:
      - seq_logs:/data
volumes:
  postgres_database:
    external: true
  seq_logs:
    external: true